config/routes.rb
Rails.application.routes.draw do
  resources :charges, only: [:new, :create]
  get 'charges/downgrade' => 'charges#downgrade'
  resources :wikis
  resources :collaborators, only: [:create, :destroy]
  devise_for :users
  get 'about' => 'welcome#about'
  root 'welcome#index'
  mount EpicEditor::Engine => "/"
end

app/models/amount.rb
class Amount
  def self.default
    10_00
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :give_standard_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :collaborators
  has_many :wikis, through: :collaborators

  validates :role, presence: true

  enum role: [:standard, :premium, :admin]

  def collaborates_on(wiki_id)
    collaborators.where(wiki_id: wiki_id).first
  end

  private
  def give_standard_role
    self.role ||= :standard
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user #its creator
  has_many :collaborators
  has_many :users, through: :collaborators

  validates_presence_of :title, :slug, :body, :user

  scope :public_wikis, -> { where(private: false) }
  scope :visible_to, -> (user) { user ? all : public_wikis }

  def public?
    !private
  end

  def owner
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!

  def create
    customer = Stripe::Customer::create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Blocipedia membership - #{current_user.email}",
      currency: "usd"
    )

   flash[:notice] = "Thanks for upgrading your account, #{current_user.email}!"
   current_user.premium!
   redirect_to edit_user_registration_path(current_user)

   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Blocipedia membership - #{current_user.email}",
     amount: Amount.default
   }
  end

  def downgrade
    current_user.standard!
    current_user.wikis.each do |wiki|
      wiki.update(private: false)
    end
    flash[:notice] = "Your account has been downgraded to #{current_user.role}, #{current_user.email}!"
    redirect_to edit_user_registration_path(current_user)
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :authenticate_user!

  def create
    @collaborator = Collaborator.new(collaborator_params)

    if @collaborator.save
      flash[:notice] = "Collaborator saved successfully."
    else
      flash[:alert] = "Unable to create collaborator. Please try again."
    end

    respond_to do |format|
      format.html #{ redirect_to edit_wiki_path(@collaborator.wiki_id) }
      format.js
    end
  end

  def destroy
    @collaborator = get_collaborator

    if @collaborator.destroy
      flash[:notice] = "Collaborator deleted successfully."
    else
      flash[:alert] = "Unable to delete collaborator. Please try again."
    end

    respond_to do |format|
      format.html #{ redirect_to edit_wiki_path(@collaborator.wiki_id) }
      format.js
    end
  end

  private
  def collaborator_params
    params.require(:collaborator).permit(:wiki_id, :user_id)
  end

  def get_collaborator
    begin
      Collaborator.find(params[:id])
    rescue
      flash[:alert] = "Unable to find that collaborator."
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    @wikis = policy_scope(Wiki)
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki saved successfully."
      redirect_to @wiki
    else
      flash[:alert] = "Unable to create wiki. Please try again."
      render :new
    end
  end

  def show
    @wiki = get_wiki
  end

  def edit
    @wiki = get_wiki
  end

  def update
    @wiki = get_wiki
    @wiki.assign_attributes(wiki_params)

    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki updated successfully."
      redirect_to @wiki
    else
      flash[:alert] = "Unable to update wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = get_wiki

    if @wiki.destroy
      flash[:notice] = "Wiki deleted successfully."
      redirect_to wikis_path
    else
      flash[:alert] = "Unable to delete wiki. Please try again."
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def get_wiki
    begin
      Wiki.visible_to(current_user).friendly.find(params[:id])
    rescue
      flash[:alert] = "Unable to find that wiki."
      redirect_to wikis_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true, 
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.haml
= form_tag charges_path do
  %h4 Click below to upgrade account
  %script.stripe-button{ src: "https://checkout.stripe.com/checkout.js", data_key: "#{@stripe_btn_data[:key]}", data_amount: @stripe_btn_data[:amount], data_description: "#{@stripe_btn_data[:description]}"}

app/views/collaborators/create.js.haml
- if @collaborator.valid?
  $("#userid-#{@collaborator.user_id}").html('#{link_to "Remove Collaborator", collaborator_path(@collaborator), method: :delete, id: "userid-#{@collaborator.user_id}", remote: true}');
- else
  $('.flash').prepend("
  .alert.alert-danger>
    %button.close{"data-dismiss" => "alert", :type => "button"} &times;
    = flash.now[:alert]
  ");

app/views/collaborators/destroy.js.haml
- if @collaborator.destroyed?
  $("#userid-#{@collaborator.user_id}").html('#{link_to "Add Collaborator", collaborators_path(collaborator: {user_id: @collaborator.user_id, wiki_id: @collaborator.wiki_id}), method: :post, id: "userid-#{@collaborator.user_id}", remote: true}');
- else
  $('.flash').prepend("
  .alert.alert-danger>
    %button.close{"data-dismiss" => "alert", :type => "button"} &times;
    = flash.now[:alert]
  ");

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Blocipedia
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %ul.nav.nav-tabs
        %li= link_to "Welcome", root_path
        %li= link_to "Wikis", wikis_path
        %li= link_to "About", about_path

        .pull-right.user-info
          - if user_signed_in?
            Signed in as
            = current_user.email
            |
            = link_to "Edit Profile", edit_user_registration_path
            \-
            = link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            = link_to "Sign In", new_user_session_path
            \-
            = link_to "Sign Up", new_user_registration_path

      .flash
        - if flash[:notice]
          %p.alert.alert-success
            = flash[:notice]
        - elsif flash[:alert]
          %p.alert.alert-warning
            = flash[:alert]
        - elsif flash.now[:alert]
          %p.alert.alert-danger
            = flash.now[:alert]

      = yield

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/welcome/about.html.haml
%h1 About Blocipedia
%small Created by Pete McNeely in collabration with Jon Linowes
%h3
  This is a place for #{link_to "wikis", "https://en.wikipedia.org/wiki/Wiki"}.

app/views/welcome/index.html.haml
%h1 Welcome to Blocipedia!

app/views/wikis/_form.html.haml
= form_for wiki do |f|
  - if wiki.errors.any?
    .alert.alert-danger
      %h4
        = pluralize(wiki.errors.count, "error")
        \.
      %ul
        - wiki.errors.full_messages.each do |msg|
          %li= msg
  = form_group_tag(wiki.errors[:title]) do
    = f.label :title
    = f.text_field :title, class: 'form-control', placeholder: "Enter wiki title"
  = form_group_tag(wiki.errors[:body]) do
    = f.label :body
    = f.hidden_field :body, id: 'hidden_wiki_body'
    #epiceditor
      = f.text_area :body, rows: 8, class: 'form-control', id: 'wiki_body', placeholder: "Enter wiki body"
  - if current_user.premium? || current_user.admin?
    .form-group
      = f.label :private, class: "checkbox" do
        = f.check_box :private
        Private Wiki
  - else
    = f.hidden_field :private, id: 'hidden_wiki_private'
  .form-group
    = f.submit "Save", class: 'btn btn-success', onclick: 'update_data()'
:javascript
  var opts = {
    textarea: wiki_body,
    clientSideStorage: false,
    theme: { base: '../../../themes/base/epic_editor.css'
          , preview: '../../../themes/preview/github.css'
          , editor: '../../../themes/editor/epic-dark.css'
          }
  };
  var editor = new EpicEditor(opts).load();
  function update_data()
  {
    var hidden_wiki_body = document.getElementById('hidden_wiki_body');
    hidden_wiki_body.value = editor.getElement('editor').body.innerHTML;

    var hidden_wiki_private = document.getElementById('hidden_wiki_private');
    hidden_wiki_private.value = false;
  };

app/views/wikis/edit.html.haml
%h1 Edit Wiki
%div
  = render partial: 'form', locals: {wiki: @wiki}
%br/
- if @wiki.private?
  %h4
    %em Collaborators
  %br/
  - if @wiki.owner == current_user || current_user.admin?
    %table
      - User.all.each do |user|
        %tr
          - collaborator = user.collaborates_on(@wiki.id)
          %td= user.email
          %td
            - if collaborator
              = link_to "Remove Collaborator", collaborator_path(collaborator), method: :delete, id: "userid-#{user.id}", remote: true
            - else
              = link_to "Add Collaborator", collaborators_path(collaborator: {user_id: user.id, wiki_id: @wiki.id}), method: :post, id: "userid-#{user.id}", remote: true
  - else
    - User.all.each do |user|
      - collaborator = user.collaborates_on(@wiki.id)
      - if collaborator
        = user.email
        |

app/views/wikis/index.html.haml
%h1 Wikis
.row
  .col-md-8
    - if @wikis.any?
      - @wikis.each do |wiki|
        %div
          %h4= link_to wiki.title, wiki
          %small
            submitted #{time_ago_in_words(wiki.created_at)} ago by #{wiki.user.email}
    - else
      %h4 There are no wikis yet!
      %br/
      %p You should totally create one.
  .col-md-4
    = button_to "Create Wiki", new_wiki_path, class:"btn btn-success", method: :get

app/views/wikis/new.html.haml
%h1 New Wiki
%div
  = render partial: 'form', locals: {wiki: @wiki}

app/views/wikis/show.html.haml
%div
  %h2
    = @wiki.title
    %div
      %small
        submitted #{time_ago_in_words(@wiki.created_at)} ago by #{@wiki.user.email}#{"(private)" if @wiki.private?}
  %div
    = markdown(@wiki.body)
  .row
    = link_to "Edit Wiki", edit_wiki_path(@wiki), class:"btn btn-success", method: :get
    = link_to "Delete Wiki", @wiki, class:"btn btn-danger", method: :delete
:javascript
  blocmetrics.report("#{@wiki.title}");